[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"

[build.buildArguments]
NEXT_PUBLIC_API_URL = "${{API_URL}}"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

